# This is an optional template for secrets, not recommended for production!
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets

stringData:
  GITLAB_ROOT_PASSWORD: {{ .Values.gitlabRootPassword }}
  PG_PASSWORD: {{ .Values.postgresql.password }}
