apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"

spec:
  selector:
    app: gitlab
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: NodePort
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: "{{ .Release.Name }}-ingress"
# spec:
#   rules:
#   - host: john.gitlab.com
#     http:
#       paths:
#       - path: /
#         backend:
#           service:
#             name: "{{ .Release.Name }}-service"
#             port: 80
#   # Minikube specific configuration (modify as needed)
#   ingressClassName: ingress-dns  # Assuming you have the ingress-dns addon enabled

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  "{{ .Release.Name }}-ingress"
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: john.gitlab.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: "{{ .Release.Name }}-service"
            port:
              number: 80
  # Windows specific configuration (using minikube service IP)
  ingressClassName: none  # Disable class-based routing
  backend:
    service:
      name: kubernetes  # Service name for Minikube API server on Windows
      port:
        number: 8080  # Default API server port