redis:
  enabled: false

# External Redis parameters
externalRedis:
  # -- External Redis server host
  host: "my-redis-master.redis.svc.cluster.local"
  # -- External Redis username
  username: ""
  # -- External Redis password
  password: "JhFlBZdJxC"
  # -- External Redis server port
  port: 6379
  # -- The name of an existing secret with Redis credentials (must contain key `redis-password`).
  # When it's set, the `externalRedis.password` parameter is ignored
  existingSecret: ""
  # -- External Redis Secret annotations
  secretAnnotations: {}