postgresql:
  install: false
redis:
  install: false
certmanager:
  install: false

global:
  psql:
    host: my-postgresql.postgres.svc.cluster.local
    port: 5432
    username: postgres
    password:
      secret: my-gitlab-postgresql
      key: postgresql-password
    database: gitlab_db

  redis:
    auth:
      enabled: true
      secret: my-gitlab-redis
      key: redis-password
    host: my-redis-master.redis.svc.cluster.local
    port: 6379

certmanager-issuer:
  # The email address to register certificates requested from Let's Encrypt.
  # Required if using Let's Encrypt.
  email: john.apisits@gmail.com
