# This is an optional template for secrets, not recommended for production!
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"

stringData:
  REGISTRY_HTTP_SECRET: {{ .Values.registryHttpSecret }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.password }}
